# Generated by Django 2.1.3 on 2018-11-28 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Desktop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('processor', models.CharField(max_length=30)),
                ('security', models.CharField(max_length=100)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('ram', models.CharField(max_length=5)),
                ('storage', models.CharField(max_length=10)),
                ('status', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('processor', models.CharField(max_length=30)),
                ('security', models.CharField(max_length=100)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('ram', models.CharField(max_length=5)),
                ('storage', models.CharField(max_length=10)),
                ('hdd_cover', models.CharField(choices=[('P', 'Present'), ('A', 'Absent')], max_length=1)),
                ('battery', models.CharField(choices=[('P', 'Present'), ('A', 'Absent')], max_length=1)),
                ('status', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Computers',
        ),
    ]
