# Generated by Django 2.1.3 on 2018-11-28 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20181128_1513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laptop',
            name='battery',
        ),
        migrations.AlterField(
            model_name='laptop',
            name='hdd_cover',
            field=models.CharField(choices=[('Cover Present', 'Present'), ('Cover Absent', 'Absent')], max_length=20),
        ),
    ]
