# Generated by Django 2.1.3 on 2018-11-28 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20181128_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='battery',
            field=models.CharField(choices=[('Battery Present', 'Present'), ('Battery Absent', 'Absent')], default='choose', max_length=15),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='hdd_cover',
            field=models.CharField(choices=[('Cover Present', 'Present'), ('Cover Absent', 'Absent')], default='choose', max_length=15),
        ),
    ]
