# Generated by Django 2.1.3 on 2018-11-29 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20181128_1642'),
    ]

    operations = [
        migrations.RenameField(
            model_name='other',
            old_name='text',
            new_name='item',
        ),
    ]
