# Generated by Django 2.1.3 on 2018-11-29 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_auto_20181129_1729'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Other',
            new_name='Generic',
        ),
    ]
